
package pdi;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;

/**
 *
 * @author informatica
 */
public class PanelImagenOriginal extends javax.swing.JPanel {
    private BufferedImage bufferImage;
    public PanelImagenOriginal(int width, int eight, String urlImage) {
        initComponents();
        
        this.setBounds(0, 0, width, eight);
        this.setBackground(Color.red);
        this.setLayout(null);
        
        try {
            File entrada = new File(urlImage);
            bufferImage = ImageIO.read(entrada);           
        }catch(Exception ex){
            System.err.println("Error: " + ex.getMessage());
        }

    }

     @Override
    public void paint(Graphics g) {
        g.drawImage(bufferImage,0,0,this);
        this.setOpaque(false);
        super.paint(g);
    }
    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
